table_name: orders
schema_name: retail

rcv_layer: rcv
l0_layer: l0
quarantine_layer: quarantine

rcv_format: csv
l0_format: csv
quarantine_format: csv

columns:
  - name: id
    type: string
  - name: customer_id
    type: string
  - name: product_id
    type: string
  - name: quantity
    type: int
  - name: price
    type: decimal
  - name: order_date
    type: datetime

validation:
  validate_file: true
  validate_schema: true
