schema_name: retail
table_name: province

l1_layer: l1
l1_format: parquet

columns:
  - name: province_id
    type: string
    db_type: VARCHAR
    max_length: 20
    primary_key: true

  - name: province_name
    type: string
    db_type: VARCHAR
    max_length: 255
    not_null: true

  - name: process_date
    type: timestamp
    db_type: TIMESTAMP
    not_null: not_null

  - name: source_file
    type: string
    db_type: VARCHAR
    max_length: 255
    not_null: true

load_database:
  load_strategy: upsert
  primary_key: province_id